name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GDRIVE_CREDENTIALS_DATA }}'
        
    - name: Test with pytest
      run: |
        touch test
        echo '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > test
        gcloud auth activate-service-account --key-file ./test
        gsutil cp gs://group-22-bucket/jigsaw-toxic-comment-classification-challenge/test.csv ./data/raw
        gsutil cp gs://group-22-bucket/jigsaw-toxic-comment-classification-challenge/train.csv ./data/raw
        gsutil cp gs://group-22-bucket/jigsaw-toxic-comment-classification-challenge/test_labels.csv ./data/raw
        pip install pytest coverage
        coverage run -m pytest tests/
        coverage report -m
